### ISSUE TITLE
Incompatible package!

### ISSUE THREAD

**Issue by Judy2424** [YangYangGirl/BoS#1]
Hello! 
Among the dependencies you provided, the packages are not compatible, especially mmcv, mmcv-full, mmdet, torch, and cuda version. Please tell me a possible solution, such as a possible virtual environment yaml.

thank you!

**Comment by YangYangGirl** [comment]
Thank you for your interest in our work. You can find the [environment.yaml](https://github.com/YangYangGirl/BoS/blob/main/environment.yaml) attached in the repo. Then, use the following command to initialize the environment: conda env create -f environment.yaml

**Comment by YangYangGirl** [comment]
<img width="724" alt="image" src="https://github.com/user-attachments/assets/20148957-fc45-4d44-b02f-c2ee8216f859">
