### ISSUE TITLE
How can I calculate the RMSE between actual and estimated mAP?

### ISSUE THREAD

**Issue by kh12043** [YangYangGirl/BoS#2]
I couldn’t find the code for calculating the RMSE between the actual and estimated mAP values in Table 1 or Table 2. Could you provide this code?

Additionally, could you share the pretrained model used in your experiments? The link provided in the README doesn’t contain the model.

Thank you!

**Comment by YangYangGirl** [comment]
Thanks for your interest in our work. I apologize that the online link for this model is no longer working, but I provide the model [config] (https://drive.google.com/drive/folders/1zAFcSgl1vfzg0BUnyJqg8t_9FkZIXA5h) used in my experiments for ease of understanding. 
The code for calculating the RMSE between the actual and estimated mAP values are provided below:
rmse = np.sqrt(np.mean((true - mAP_pred) ** 2))
